enum LexemeType {
    case Binary_literal
    case Octal_literal
    case Octal_digit
    case Octal_literal_character
    case Octal_literal_characters
    case Pure_decimal_digits
    case Hexadecimal_literal
    case Sign
    case Hexadecimal_fraction
    case Decimal_literal
    case Floating_point_e
    case Floating_point_p
    case Hexadecimal_exponent
    case Decimal_exponent
    case Decimal_fraction
    case Decimal_digit
    case Escaped_character
    case Interpolated_text_item
    case Decimal_literal_character
    case Decimal_literal_characters
    case Hexadecimal_digit
    case Interpolated_string_literal
    case Quoted_text
    case Quoted_text_item
    case Hexadecimal_literal_character
    case Hexadecimal_literal_characters
    case DOT
    case LCURLY
    case LPAREN
    case LBRACK
    case RCURLY
    case RPAREN
    case RBRACK
    case COMMA
    case COLON
    case SEMI
    case LT
    case GT
    case UNDERSCORE
    case BANG
    case QUESTION
    case AT
    case AND
    case SUB
    case EQUAL
    case OR
    case DIV
    case ADD
    case MUL
    case MOD
    case CARET
    case TILDE
    case Identifier
    case Identifier_characters
    case Identifier_head
    case Identifier_character
    case Implicit_parameter_name
    case Platform
    case Platform_name
    case Platform_version
    case Static_string_literal
    case numeric_literal
    case string_literal
    case Binary_literal_characters
    case Binary_literal_character
    case Binary_digit
    case boolean_literal
    case nil_literal
    case integer_literal
    case WS
    case Block_comment
    case Line_comment
    case access_level_modifier
    case architecture
    case array_literal
    case array_literal_item
    case array_literal_items
    case arrow_operator
    case assignment_operator
    case assignment_statement
    case associativity
    case associativity_clause
    case attribute
    case attribute_argument_clause
    case attribute_name
    case attributes
    case availability_argument
    case availability_arguments
    case availability_condition
    case balanced_token
    case balanced_tokens
    case binary_expression
    case binary_expressions
    case binary_operator
    case branch_statement
    case break_statement
    case negate_prefix_operator
    case Floating_point_literal
    case build_AND
    case build_OR
    case build_configuration
    case build_configuration_else_clause
    case build_configuration_elseif_clause
    case build_configuration_elseif_clauses
    case build_configuration_statement
    case capture_list
    case capture_list_item
    case capture_list_items
    case capture_specifier
    case case_condition
    case case_item_list
    case case_label
    case catch_clause
    case catch_clauses
    case class_body
    case class_declaration
    case class_name
    case class_requirement
    case closure_expression
    case closure_signature
    case code_block
    case compiler_control_statement
    case condition
    case condition_clause
    case condition_list
    case conditional_operator
    case conformance_requirement
    case constant_declaration
    case context_sensitive_keyword
    case continue_statement
    case control_transfer_statement
    case declaration
    case declaration_modifier
    case declaration_modifiers
    case declarations
    case default_argument_clause
    case default_label
    case defer_statement
    case deinitializer_declaration
    case dictionary_literal
    case dictionary_literal_item
    case dictionary_literal_items
    case didSet_clause
    case do_statement
    case element_name
    case else_clause
    case enum_case_name
    case enum_case_pattern
    case enum_declaration
    case enum_name
    case expression
    case expression_element
    case expression_element_list
    case expression_list
    case expression_pattern
    case extension_body
    case extension_declaration
    case external_parameter_name
    case fallthrough_statement
    case file_name
    case for_in_statement
    case for_init
    case for_statement
    case function_body
    case function_declaration
    case function_head
    case function_name
    case function_result
    case function_signature
    case generic_argument
    case generic_argument_clause
    case generic_argument_list
    case generic_parameter
    case generic_parameter_clause
    case generic_parameter_list
    case getter_clause
    case getter_keyword_clause
    case getter_setter_block
    case getter_setter_keyword_block
    case guard_statement
    case identifier
    case identifier_list
    case identifier_pattern
    case if_statement
    case implicit_member_expression
    case import_declaration
    case import_kind
    case import_path
    case import_path_identifier
    case in_out_expression
    case infix_operator_attributes
    case infix_operator_declaration
    case initializer
    case initializer_body
    case initializer_declaration
    case initializer_head
    case label_name
    case labeled_statement
    case line_control_statement
    case line_number
    case literal
    case literal_expression
    case local_parameter_name
    case loop_statement
    case operating_system
    case operator_declaration
    case optional_binding_condition
    case optional_binding_continuation
    case optional_binding_continuation_list
    case optional_binding_head
    case optional_pattern
    case parameter
    case parameter_clause
    case parameter_clauses
    case parameter_list
    case parenthesized_expression
    case pattern
    case pattern_initializer
    case pattern_initializer_list
    case platform_testing_function
    case postfix_expression
    case dot_operator_character
    case operator_character
    case Operator_following_character
    case postfix_operator
    case operator_head
    case Operator_head_other
    case dot_operator_head
    case postfix_operator_declaration
    case precedence_clause
    case precedence_level
    case prefix_expression
    case prefix_operator
    case prefix_operator_declaration
    case primary_expression
    case protocol_associated_type_declaration
    case protocol_body
    case protocol_composition_type
    case protocol_declaration
    case protocol_identifier
    case protocol_identifier_list
    case protocol_initializer_declaration
    case protocol_member_declaration
    case protocol_member_declarations
    case protocol_method_declaration
    case protocol_name
    case protocol_property_declaration
    case protocol_subscript_declaration
    case range_operator
    case raw_value_assignment
    case raw_value_literal
    case raw_value_style_enum
    case raw_value_style_enum_case
    case raw_value_style_enum_case_clause
    case raw_value_style_enum_case_list
    case raw_value_style_enum_member
    case raw_value_style_enum_members
    case repeat_while_statement
    case requirement
    case requirement_clause
    case requirement_list
    case return_statement
    case same_type_equals
    case same_type_requirement
    case self_expression
    case setter_clause
    case setter_keyword_clause
    case setter_name
    case statement
    case statement_label
    case statements
    case struct_body
    case struct_declaration
    case struct_name
    case subscript_declaration
    case subscript_head
    case subscript_result
    case superclass_expression
    case superclass_initializer_expression
    case superclass_method_expression
    case superclass_subscript_expression
    case switch_case
    case switch_cases
    case switch_statement
    case throw_statement
    case top_level
    case top_level_declaration
    case trailing_closure
    case try_operator
    case tuple_pattern
    case tuple_pattern_element
    case tuple_pattern_element_list
    case tuple_type
    case tuple_type_body
    case tuple_type_element
    case tuple_type_element_list
    case type
    case type_annotation
    case type_casting_operator
    case type_identifier
    case type_inheritance_clause
    case type_inheritance_list
    case type_name
    case typealias_assignment
    case typealias_declaration
    case typealias_head
    case typealias_name
    case union_style_enum
    case union_style_enum_case
    case union_style_enum_case_clause
    case union_style_enum_case_list
    case union_style_enum_member
    case union_style_enum_members
    case value_binding_pattern
    case variable_declaration
    case variable_declaration_head
    case variable_name
    case where_clause
    case where_expression
    case while_statement
    case wildcard_expression
    case wildcard_pattern
    case willSet_clause
    case willSet_didSet_block
    case _operator
}